
version: "3.8"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            NODE_ENV: development
            PORT: 3333
        ports:
            - "8080:3333"